import type { Metadata } from "next";
import PageHero from "@/components/PageHero";
import Link from "next/link";
import ArticleEnhancement from "@/components/ArticleEnhancement";
export const metadata: Metadata = { title: "Hot-Water Rebates Albury & Wodonga", description: "A practical guide to checking NSW, Victorian and federal hot-water incentives without assuming eligibility.", alternates: { canonical: "/blog/hot-water-rebates-albury-wodonga" } };
export default function Post(){return <><PageHero eyebrow="Rebates and incentives" title="Hot-water rebates for Albury and Wodonga households" intro="Your state, existing system, chosen product and provider can all affect eligibility. Check the official program before agreeing to an upgrade." image="/images/heat-pump.webp"/><main><article className="section article">
  <p className="lead">Albury residents are covered by NSW programs; Wodonga residents are covered by Victorian programs. Some eligible solar and heat-pump systems may also create federal Small-scale Technology Certificates.</p>
  <div className="notice"><strong>Information checked September 2026</strong><p>Programs, funding and eligibility can change. Treat this article as a starting point—not a promise that a household or product will qualify.</p></div>
  <h2>Albury and other NSW properties</h2><p>NSW efficiency programs may offer discounts for eligible upgrades from existing water heating to approved efficient systems. The value normally depends on the installation, equipment and certificate arrangements rather than being one flat amount for every home.</p><p><a className="text-link" href="https://www.energy.nsw.gov.au/" target="_blank" rel="noopener noreferrer">Check NSW Climate and Energy Action</a></p>
  <h2>Wodonga and other Victorian properties</h2><p>Victorian households may have access to energy-upgrade discounts and eligible hot-water support. Requirements can include property, income, existing system, product and authorised-provider conditions.</p><p><a className="text-link" href="https://www.energy.vic.gov.au/" target="_blank" rel="noopener noreferrer">Check Victorian Energy Upgrades</a> · <a className="text-link" href="https://www.solar.vic.gov.au/" target="_blank" rel="noopener noreferrer">Check Solar Victoria</a></p>
  <h2>Federal certificates</h2><p>Eligible solar and heat-pump water heaters can create Small-scale Technology Certificates. These are commonly assigned in exchange for an upfront discount, but the amount varies.</p><p><a className="text-link" href="https://cer.gov.au/" target="_blank" rel="noopener noreferrer">Check the Clean Energy Regulator</a></p>
  <ArticleEnhancement kind="rebates"/>
  <div className="section-actions"><Link className="button button-dark" href="/services/heat-pump-hot-water">Explore heat pumps</Link><Link className="text-link" href="/contact">Request a local quote</Link></div>
</article></main></>}
